### ISSUE TITLE
BGM not playing any music

### ISSUE THREAD

**Issue by vgcchoirboy** [wizzomafizzo/MiSTer_BGM#2]
I followed all steps exactly and have been getting this message 
![image](https://user-images.githubusercontent.com/103548823/163088644-1e5b9068-257b-431c-a5c6-5988991e9f75.png)

**Comment by wizzomafizzo** [comment]
Hi. I think you can ignore this error, I can put in a fix so it doesn't show anymore though. I think it's happening because you haven't got any music in your music folder yet (which I instructed you to do in the readme so no that's my fault)

If you continue as normal, put your music in and then reboot the mister does everything start playing as it should?

**Comment by vgcchoirboy** [comment]
i don't know what it was. i renamed the music back from _boot.mp3 back to normal. eventually it started working. I did have music in there when i first started it. creating the music folder ahead of time
